### ISSUE TITLE
Anti-pattern: No Rolling Updates

### ISSUE THREAD

**Issue by akondasif** [patrikduch/netcore-microservices#2]
Dear Colleague,

We are looking to find ways to help developers find security anti-patterns, i.e., violation of security best practices in Kubernetes manifests.

We have noticed an instance of not using rolling updates. Rolling updates helps to automatically apply continuous updates. Without continuous updates, a Kubernetes cluster will be susceptible to a denial of service attack, according to researchers: https://arxiv.org/pdf/2006.15275.pdf .

Location of anti-pattern:

https://github.com/patrikduch/netcore-microservices/blob/e594cf72913e775fb9932a563a3b6e43bedf4532/deployment/aks/services/discount/discount-db/discount-db-deployment.yaml#L6

**Comment by patrikduch** [comment]
Thanks @akondasif.  Configuration has been updated.
